export const NOTIFICATION_SUBSCRIPTION_PREFIX = "NOTE_SUB_";
export const NEWSFEED_VIDEO_SUBSCRIPTION_PREFIX = "NEWSFEED_VIDEO_SUB_";
export const NEWSFEED_IMAGE_SUBSCRIPTION_PREFIX = "NEWSFEED_IMAGE_SUB_";
export const NEWSFEED_NOTE_SUBSCRIPTION_PREFIX = "NEWSFEED_NOTE_SUB_";
